#############################################################################
#
# This script demonstrates the production of various industry output and 
# employment multipliers using the guidance provided in the ABS document:
# 5246.0 - Information Paper - Introduction to Output Multipliers (1996-1997)
#
#############################################################################


library(tidyverse) # load tidyverse for data manipulation


# abs-io-example-table1.csv contains a subset of the data found in Table 1 on page 5
# this table represent an industry flow matrix, currently published as Table 5 in the
# consolidated ABS Australian National Accounts: Input-Output Tables (5209.0.55.001)
table1 <- read.csv("data/abs-io-example-table1.csv", header = TRUE, row.names = 1)

# as i/o tables commonly include additional rows and columns which are not part of the
# flows between industries, specifying the number of industries allows isolating just that data
numIndustries <- 7

# create a square matrix representing just the industry flow data
table1_industries <- as.matrix(table1[1:numIndustries,1:numIndustries])

# we will need a value to represent the total output of each industry
# the ABS guideance advises using the 'Australian production' row (found in Table 1)
total_output <- as.numeric(table1["Australian production",1:numIndustries])

# each value in a column's industry vector will need to be divided by the corresponding
# total_output value for that industry. to support this matrix operation, we replicate the
# total_output vector as a matrix so that it has the same number of rows as table1_industries
total_output_matrix <- matrix(rep(total_output, nrow(table1_industries)), nrow = nrow(table1_industries), byrow = TRUE)

# derive matrix A [(1) in Table 4 on page 11]
# this corresponds to a subset of the Direct Requirements Coefficients (Table 2, page 7)
A <- table1_industries / total_output_matrix

# each industry's first round effects is calculated using the column totals
# shown in (2) of Table 4 on page 11
# --
# this value reflects the amount of output from all industries of the economy to produce an extra
# dollar of output for a given industry (see #19, p. 6)
first_round_effects = colSums(A)

# calculate the Leontief inverse of matrix A [(2) in Table 4 on page 11]
A_Leontief_Inverse <- solve(diag(nrow(A)) - A)

# each industry's simple multiplier is calculated using the column totals
# shown in (2) of Table 4 on page 11
# --
# this value reflects the combined effect of the initial effects plus all the production induced
# rounds of extra output (see #22, p. 8)
simple_multipliers = colSums(A_Leontief_Inverse)

# industrial support effects are the effects of the second and sunsequent rounds of induced
# production (#25 on page 8)
industrial_support_effects <- simple_multipliers - 1 - first_round_effects
production_induced_effects <- first_round_effects + industrial_support_effects

# to create the B matrix, the A matrix needs to be extended with the following data
# from the Direct Requirements Coefficients matrix (Table 2)
# - the Wages row 
# - the Final consumption expenditure column
wages <- c(0.1245,0.1506,0.1666,0.2179,0.3114,0.3406,0.3617) # (taken from Table 2)
B <- rbind(A,wages)
consumption <- c(0.0113,0.0003,0.1395,0.0136,0.2005,0.4444,0.0851,0) # (taken from Table 2)
B <- cbind(B,consumption)

# calculate the Leontief inverse of matrix B [(2) in Table 4 on page 11]
B_Leontief_Inverse <- solve(diag(nrow(B)) - B)
# the B* matrix is formed by taking just the 7x7 industry matrix of B_Leontief_Inverse
# this corresponds to (3) in Table 4 on page 11 (this table is identified as incorrect in the ABS document)
B_Star <- B_Leontief_Inverse[-(numIndustries+1),-(numIndustries+1)]
# the total multipliers are calculated as the column totals of B*
# --
# this value reflects the private consumption expenditure which is generated by wages which result
# from the increased production output (see #26, p. 8)
total_multipliers <- colSums(B_Star)

# consumption induced effects = total multiplier - simple multiplier (see #29, p. 8-9)
consumption_induced_effects <- total_multipliers - simple_multipliers

# Reproduce Table 5, Output Multipliers, page 12
output_multipliers <- tibble(
  Industry = colnames(A),
  `Initial effects` = 1,
  `First round effects` = first_round_effects,
  `Industrial support effects` = industrial_support_effects,
  `Production induced effects` = production_induced_effects,
  `Consumption induced effects` = consumption_induced_effects,
  `Simple multipliers` = simple_multipliers,
  `Total multipliers` = total_multipliers
)


### employment multipliers

# employment multipliers require coefficients representing the number of people employed per
# $1 million of output. these are calculated by dividing the number of FTE employed persons
# in an industry by the total Australian production for that industry
# --
# the employment coefficients here are taken from Table 3 on page 10
employment_coefficients <- c(14.5496,3.7697,6.9745,10.0090,14.8719,11.8965,11.9107)

# the calcualtion of corresponding employment multipliers is achieved by multiplying the
# A, A_Leontief_Inverse and B_Star matrices prepared above by the employment coeffecients
# --
# Note that the ABS document's interpretation of 'matrix multiplication' is column-wise
# multiplication and not linear algebra dot products. To implement this, we step through
# each industry column vector, multiply that by the the aligned vector of employment
# coefficients and then obtain a sum of the values for each industry column
# --
# initial effects are the same as the employment coefficients as the initial output is 1
emp_initial_effects <- 1 * employment_coefficients

# first round effects are obtained from the A matrix (see page 17)
emp_first_round_effects <- numeric(numIndustries)
for (i in 1:numIndustries) {
  emp_first_round_effects[i] <- sum(A[, i] * employment_coefficients)
}

# simple multipliers are obtained from the A_Leontief_Inverse matrix (see page 17)
emp_simple_multipliers <- numeric(numIndustries)
for (i in 1:numIndustries) {
  emp_simple_multipliers[i] <- sum(A_Leontief_Inverse[, i] * employment_coefficients)
}

# total multipliers are obtained from the B_Star matrix (see page 17)
emp_total_multipliers <- numeric(numIndustries)
for (i in 1:numIndustries) {
  emp_total_multipliers[i] <- sum(B_Star[, i] * employment_coefficients)
}

# other eployment effects are calculated by addition/subtraction as per output multipliers
emp_industrial_support_effects <- emp_simple_multipliers - emp_initial_effects - emp_first_round_effects
emp_production_induced_effects <- emp_first_round_effects + emp_industrial_support_effects
emp_consumption_induced_effects <- emp_total_multipliers - emp_simple_multipliers

# Reproduce Table 5, Employment Multipliers, page 12
employment_multipliers <- tibble(
  Industry = colnames(A),
  `Initial effects` = emp_initial_effects,
  `First round effects` = emp_first_round_effects,
  `Industrial support effects` = emp_industrial_support_effects,
  `Production induced effects` = emp_production_induced_effects,
  `Consumption induced effects` = emp_consumption_induced_effects,
  `Simple multipliers` = emp_simple_multipliers,
  `Total multipliers` = emp_total_multipliers
)
